/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_example_hello_GoodbyeApi */

#ifndef _Included_org_example_hello_GoodbyeApi
#define _Included_org_example_hello_GoodbyeApi
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_example_hello_GoodbyeApi
 * Method:    goodbye
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_example_hello_GoodbyeApi_goodbye
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
