/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_example_hello_HelloApi */

#ifndef _Included_org_example_hello_HelloApi
#define _Included_org_example_hello_HelloApi
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_example_hello_HelloApi
 * Method:    hello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_example_hello_HelloApi_hello
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
